post = Post.create(body: "NSFL ISH")
post.comments.create(body: "WOAH")
post.comments.create(body: "wtf")
post.comments.create(body: "comment")
post.comments.create(body: "123454")
post.comments.create(body: "omg no ways")
post.comments.create(body: "disgusting")
post.comments.create(body: "hi")
post.comments.create(body: "WOAH")

post.comments.create(body: "WOAH")
post.comments.create(body: "WOAH")

Post.create(body: "CUTE DOG")
Post.create(body: "TIL: SOMETHING OMG I LEARNED SOMETHING")
Post.create(body: "RICK AND MORTY 100 YEARS")
Post.create(body: "Test")
Post.create(body: "SHHH")