post = Post.create(body: "Rick And Morty 100 Years!")
post.comments.create(body: "Meeseeks!")
post.comments.create(body: "Pirates of the Panceas")
post = Post.create(body: "TIL: Restingful Ways Of Forms")
post.comments.create(body: "WOW Rails is amazing")
post.comments.create(body: "Eh")
